//! All domain enums persisted as TEXT in SQLite.
//!
//! Each enum is generated by the `str_enum!` macro which provides:
//! - `as_str(&self) -> &'static str`
//! - `from_db_str(s: &str) -> Result<Self, CoreError>`
//! - `Display` (delegates to `as_str`)
//! - `Serialize` / `Deserialize` (as the string repr)

use serde::{Deserialize, Serialize};

use crate::error::CoreError;

/// Generates a string-backed enum suitable for SQLite TEXT columns.
macro_rules! str_enum {
    (
        $(#[$meta:meta])*
        $name:ident {
            $( $(#[$vmeta:meta])* $variant:ident => $s:literal ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum $name {
            $( $(#[$vmeta])* $variant, )+
        }

        impl $name {
            /// Return the canonical string stored in SQLite.
            pub fn as_str(&self) -> &'static str {
                match self {
                    $( Self::$variant => $s, )+
                }
            }

            /// Parse from the SQLite TEXT value; returns `CoreError::UnknownVariant` on failure.
            pub fn from_db_str(s: &str) -> Result<Self, CoreError> {
                match s {
                    $( $s => Ok(Self::$variant), )+
                    _ => Err(CoreError::UnknownVariant {
                        type_name: stringify!($name),
                        value: s.to_owned(),
                    }),
                }
            }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
                s.serialize_str(self.as_str())
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
                let raw = String::deserialize(d)?;
                Self::from_db_str(&raw).map_err(serde::de::Error::custom)
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

str_enum! {
    /// Broad classification of a source file.
    FileType {
        /// Rust source file.
        Rust          => "rust",
        /// TypeScript source file.
        TypeScript    => "typescript",
        /// JavaScript source file.
        JavaScript    => "javascript",
        /// Python source file.
        Python        => "python",
        /// Java source file.
        Java          => "java",
        /// C source file.
        C             => "c",
        /// C++ source file.
        Cpp           => "cpp",
        /// Go source file.
        Go            => "go",
        /// Markdown document.
        Markdown      => "markdown",
        /// JSON data file.
        Json          => "json",
        /// TOML configuration file.
        Toml          => "toml",
        /// YAML configuration file.
        Yaml          => "yaml",
        /// Plain text file.
        Text          => "text",
        /// Binary or non-text file.
        Binary        => "binary",
        /// Any other file type.
        Other         => "other",
    }
}

str_enum! {
    /// How a file was discovered.
    DiscoveryClass {
        /// Found by walking the filesystem.
        Filesystem  => "filesystem",
        /// Found via a VCS graph (e.g., git tree).
        Vcs         => "vcs",
        /// Found via explicit manifest / config reference.
        Manifest    => "manifest",
    }
}

str_enum! {
    /// Security classification of a file occurrence.
    SecurityState {
        /// No secrets found.
        Clean    => "clean",
        /// Secret(s) detected.
        Flagged  => "flagged",
        /// Scan not yet performed.
        Pending  => "pending",
        /// Scan skipped (e.g., binary file).
        Skipped  => "skipped",
    }
}

str_enum! {
    /// Whether the file still exists at the head of the index generation.
    ExistenceState {
        /// File is present.
        Present => "present",
        /// File has been deleted.
        Deleted => "deleted",
    }
}

str_enum! {
    /// Whether the index data for this file is up-to-date.
    FreshnessState {
        /// Index data is current.
        Fresh      => "fresh",
        /// File exists but has not yet been indexed.
        Unindexed  => "unindexed",
        /// Content changed; re-indexing required.
        Stale      => "stale",
    }
}

str_enum! {
    /// State of the secret scan for a file occurrence.
    SecretScanState {
        /// Scan completed; no secrets found.
        Clean    => "clean",
        /// Scan completed; secrets found.
        Flagged  => "flagged",
        /// Scan not yet run.
        Pending  => "pending",
    }
}

str_enum! {
    /// Semantic index state for a retrieval unit.
    SemanticState {
        /// Embedding is current.
        Current    => "current",
        /// Embedding is outdated.
        Outdated   => "outdated",
        /// Embedding not yet generated.
        Pending    => "pending",
    }
}

str_enum! {
    /// Lexical index state for a retrieval unit.
    LexicalState {
        /// FTS index is current.
        Current    => "current",
        /// FTS index is outdated.
        Outdated   => "outdated",
        /// Not yet indexed.
        Pending    => "pending",
    }
}

str_enum! {
    /// Reason a symbol occurrence was invalidated.
    InvalidationReason {
        /// Source file was modified.
        FileModified    => "file_modified",
        /// Source file was deleted.
        FileDeleted     => "file_deleted",
        /// Index generation expired.
        GenerationExpired => "generation_expired",
        /// Manually invalidated.
        Manual          => "manual",
    }
}

str_enum! {
    /// Kind of a symbol (mirrors common language constructs).
    SymbolKind {
        /// Function or free function.
        Function    => "function",
        /// Method on a type.
        Method      => "method",
        /// Class or struct.
        Class       => "class",
        /// Interface or trait.
        Interface   => "interface",
        /// Module or namespace.
        Module      => "module",
        /// Constant value.
        Constant    => "constant",
        /// Variable or field.
        Variable    => "variable",
        /// Type alias.
        TypeAlias   => "type_alias",
        /// Macro definition.
        Macro       => "macro",
    }
}

str_enum! {
    /// Type of relationship between two structural nodes.
    RelType {
        /// Child–parent containment.
        Contains    => "contains",
        /// Import / use dependency.
        Imports     => "imports",
        /// Inheritance relationship.
        Inherits    => "inherits",
        /// Implementation of an interface/trait.
        Implements  => "implements",
        /// Call-graph edge.
        Calls       => "calls",
        /// Reference without a call.
        References  => "references",
    }
}

str_enum! {
    /// How a dependency relationship was determined.
    DependencyBasis {
        /// Declared in a manifest (Cargo.toml, package.json, …).
        Manifest    => "manifest",
        /// Inferred from import/use statements.
        Import      => "import",
        /// Determined by dynamic analysis.
        Dynamic     => "dynamic",
    }
}

str_enum! {
    /// Conflict or ambiguity resolution outcome.
    Resolution {
        /// Resolved without conflict.
        Resolved    => "resolved",
        /// Conflict detected, not yet resolved.
        Conflicted  => "conflicted",
        /// Ignored intentionally.
        Ignored     => "ignored",
    }
}

str_enum! {
    /// Kind of build/package artifact.
    ArtifactType {
        /// Compiled binary executable.
        Binary      => "binary",
        /// Shared or static library.
        Library     => "library",
        /// Test binary.
        Test        => "test",
        /// Example binary.
        Example     => "example",
    }
}

str_enum! {
    /// Authority level of a source or agent.
    Authority {
        /// First-party (this repository).
        FirstParty  => "first_party",
        /// Third-party dependency.
        ThirdParty  => "third_party",
        /// Unknown or mixed.
        Unknown     => "unknown",
    }
}

str_enum! {
    /// Whether an entity has been verified.
    VerificationState {
        /// Verification passed.
        Verified    => "verified",
        /// Verification failed.
        Failed      => "failed",
        /// Not yet verified.
        Pending     => "pending",
    }
}

str_enum! {
    /// Semantic compatibility class for a version change.
    CompatibilityClass {
        /// Backwards-compatible change.
        Compatible      => "compatible",
        /// Breaking change.
        Breaking        => "breaking",
        /// Unknown compatibility.
        Unknown         => "unknown",
    }
}

str_enum! {
    /// Source type for a revision.
    SourceType {
        /// Git repository.
        Git         => "git",
        /// Archive (zip, tar, …).
        Archive     => "archive",
        /// Local directory snapshot.
        Local       => "local",
    }
}

str_enum! {
    /// Category of a background task.
    TaskType {
        /// Indexing task.
        Indexing        => "indexing",
        /// Secret scanning task.
        SecretScan      => "secret_scan",
        /// Embedding generation task.
        Embedding       => "embedding",
        /// Cleanup / garbage collection task.
        Cleanup         => "cleanup",
    }
}

str_enum! {
    /// Execution state of a background task.
    TaskState {
        /// Waiting to be picked up.
        Queued      => "queued",
        /// Currently executing.
        Running     => "running",
        /// Completed successfully.
        Completed   => "completed",
        /// Failed with an error.
        Failed      => "failed",
        /// Cancelled before completion.
        Cancelled   => "cancelled",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_type_round_trips() {
        for &ft in &[
            FileType::Rust,
            FileType::TypeScript,
            FileType::Binary,
            FileType::Other,
        ] {
            assert_eq!(FileType::from_db_str(ft.as_str()).unwrap(), ft);
        }
    }

    #[test]
    fn unknown_variant_returns_error() {
        assert!(FileType::from_db_str("not_a_type").is_err());
    }

    #[test]
    fn display_equals_as_str() {
        assert_eq!(format!("{}", SymbolKind::Function), "function");
    }

    #[test]
    fn serde_round_trip() {
        let original = TaskState::Running;
        let json = serde_json::to_string(&original).unwrap();
        let decoded: TaskState = serde_json::from_str(&json).unwrap();
        assert_eq!(original, decoded);
    }
}
